### PR TITLE
Noncommercial Organizations: Avoid limiting to "use" only

### PR DESCRIPTION
**Pull request by kemitchell**
This PR addresses the concern about "use" alone being too restrictive in Noncommercial Organizations, a part of #24.

### CODE REVIEW

**Comment by kemitchell** [comment]
@careed95073, here's a response to your concerns about "use" in the Noncommercial Organizations section of the Polyform drafts. Have a look and let me know what you think?

**Comment by heathermeeker** [comment]
I see the issue with "use" being read narrowly. I am not sure the proposal works for me.  Maybe exercising the license instead of reliance?  Reliance has a legal term of art meaning for me.

**Comment by kemitchell** [comment]
Is there a plainer-English way of saying "exercise this license"?

**Comment by heathermeeker** [comment]
There are other instances of “use” so do we need to define use as use or anything else requiring a license?

**Comment by kemitchell** [comment]
@heathermeeker from my point of view, this is the PR to review next.

**Pull request merged**
