### PR TITLE
Suggesting changes to non-compete

### PR DESCRIPTION
**Pull request by heathermeeker**
There is a typo but I can't edit it.

### CODE REVIEW

**Comment by kemitchell** [comment]
@heathermeeker Where was the typo? In a PR somewhere?

**Comment by heathermeeker** [comment]
Yes, I just submitted it.

**Comment by mlinksva** [comment]
It's not clear to me what "market your offering as an economic substitute for the software" covers. I _guess_ it is intended to cover offering the software as a service, but that seems like an economic substitute for someone else (another provider, or user self-hosting) providing the software as a service, not a substitute for "the software".

I did read https://github.com/polyformproject/polyform-licenses/issues/32#issuecomment-505204787 and understand the concept of an economic substitute, but still am not clear on effect of the language in this PR and #60.

Further, what if the licensed software is not an application, but a library?

**Comment by kemitchell** [comment]
@mlinksva thanks for pointing this out. #60 is the current going proposal for the Noncompete language, with input from Heather and I and others. I will close this one, so folks can focus on #60.

The economic-substitute concept appears in #60, as well, though it's employed in a different way.

**Comment by mlinksva** [comment]
I have the same question about the language in #60 so I made a very slightly edited version of the comment above there. 😄

**Pull request closed without merging**
