### PR TITLE
Small Business: Replace "less" with "fewer" before "employees"

### PR DESCRIPTION
**Pull request by kemitchell**
Transcribed from https://docs.google.com/document/d/1EMbmyG3CNcIL5yJmQOvffo_CZCiwLREZHR3kXvDmPsk/edit

With thanks to Steve Phillips

### CODE REVIEW

**Comment by elimisteve** [comment]
@kemitchell Thanks! :+1:

**Comment by kemitchell** [comment]
@elimisteve, may I amend to give you author credit for the commit?

**Comment by elimisteve** [comment]
@kemitchell Sure

**Comment by elimisteve** [comment]
@kemitchell Or use https://github.com/polyformproject/polyform-licenses/pull/15 ; whatever's best for you.

**Pull request merged**
