### PR TITLE
Allow distribution of permitted changes and new works

### PR DESCRIPTION
**Pull request by kemitchell**
This PR changes Distribution License so that when Changes and New Work License is also present, Distribution License allows distribution of changes and new works based on the software.

That way Polyform-CL-DL approximates Creative Commons' CC-BY-NC, and Polyform-DL approximates CC-BY-NC-ND.

### CODE REVIEW

**Comment by heathermeeker** [comment]
I don't think this was necessary.  A partner at Wilson whom I used to work with made this change to every license, and I was always skeptical.  The licensor only controls the right to prepare derivative works and distribute the licensor's original software.  Licensor has no other right in another party's derivative.  The party preparing derivative works has the right to enforce the copyright rights to the extent relating to those derivatives.  The right to distribute the software is a subset of the right to distribute a derivative work.  But I will not go to the mat on this point, so I approved.

**Comment by kemitchell** [comment]
@heathermeeker I have some thoughts on this, as a matter of copyright. But in the end, these are both license and contract terms.

**Comment by heathermeeker** [comment]
Technically it seems to be granting rights owned in part by licensee.

**Comment by kemitchell** [comment]
Perhaps?:

> The licensor grants you an additional copyright license to distribute copies of the software, and if these terms grant you an additional license to make changes and new works, to distribute **with** your changes and **as part of** new works, as well.  You must ensure that anyone who gets a copy of any part of the software from you also gets the text of these terms or a link to their text on <https://polyformproject.org>.

**Comment by heathermeeker** [comment]
This makes me think that making distribution changes part of the base license, and clawing them back, instead of the reverse, might be easier.  I'm getting concerned that the base license I originally wanted to create is an alphabet soup -- Polyform NC DL CL. Also I think the drafting would be easier.

**Comment by kemitchell** [comment]
Point taken. But name driving structure is tail wagging dog.

Why don't we eschew the Creative Commons style, Polyform-CL-DL convention altogether, and just come up with single-word descriptions or codenames for the license variants? Perhaps "Polyform-Basic" or "Polyform-Penrose" or just "Polyform-Noncommercial".

**Pull request merged**
